name: Chrome Extension

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm install -g npm@8.3.0
      - run: npm ci
      - run: npm run package
      - run: npm -w chrome-ext run build
      - id: tag
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: '${{ steps.tag.outputs.sha_short }}'
          releaseName: 'Aicacia Password ${{ steps.tag.outputs.sha_short }}'
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: chrome-ext/dist/aicacia-password-chrome-extension.zip
          asset_name: aicacia-password-chrome-extension.zip
          asset_content_type: application/zip
